### ISSUE TITLE
System preference doesn't work by default

### ISSUE THREAD

**Issue by ahmadawais** [pacocoursey/next-themes#20]
When I read the docs it looks like system preference is set to true by default.

`enableSystem = true`: Whether to switch between dark and light based on prefers-color-scheme

But when I implement this or just browse the demo https://next-themes-example.vercel.app/ or the one with Tailwind — even though my macOS preference is set to `dark`, the theme gets set to `light`.

This doesn't look like a sane default or a bug. My thought process is that next-themes would by default prefer the system's preference when available and only fallback to light if it's not.

Am I doing something wrong?

**Comment by ahmadawais** [comment]
On the client side when I log everything, it looks like the resolvedTheme is wrong.

![image](https://user-images.githubusercontent.com/960133/103525299-ca422b00-4ea0-11eb-97e1-c26a1a6760bf.png)


As you can see the systemTheme is `dark` but it's resolving into the `light` one for some reason.

**Comment by ahmadawais** [comment]
Even setting the system theme as default doesn't help. Can you help me figure out how should I by default prefer the user-system preference?

_app.js in Next.js currently looks like this

```js
import { ThemeProvider } from 'next-themes';

function MyApp({ Component, pageProps }) {
	return (
		<ThemeProvider attribute="class" defaultTheme="system" forcedTheme={Component.theme || undefined}>
			<Component {...pageProps} />
		</ThemeProvider>
	);
}

export default MyApp;

```

I have dark theme in macOS enabled but it's resulting in the selection of `light` theme by default.

**Comment by pacocoursey** [comment]
> This doesn't look like a sane default or a bug. My thought process is that next-themes would by default prefer the system's preference when available and only fallback to light if it's not.
>
> Am I doing something wrong?

Sounds like you're running into the same issue as #15. The documentation states:
> `defaultTheme = 'light'`: Default theme name

So by default, your app will use `light` theme, not system. You can change this by setting `defaultTheme` (basically, just read through that issue as it's the same discussion).

---

The second problem you're running into is one I plan to fix shortly: the theme is cached into localStorage immediately. This means the first time you loaded the website, it cached `light`. Now, even though you're changing `defaultTheme`, we are respecting the cache. Try calling `setTheme` or clearing the local storage cache yourself.

I'm going to remove this behavior, so that the theme isn't cached until a call to `setTheme` has been made.

**Comment by ahmadawais** [comment]
Thanks for the response. I did read through the issue. It seems like a bad default. The main purpose of this library is to be able to adopt to the user preference since it doesn't provide a UI (for setTheme which is a feature and is opt-in). Please consider making the `system` setting default.

My setup did start working I have no idea how. Bunch of cache removals and then setting themese manually etc — and now it works with:

```js

<ThemeProvider attribute="class" defaultTheme="system" forcedTheme={Component.theme || undefined}>
			<Component {...pageProps} />
		</ThemeProvider>

```

But when I set `Post.theme = `light`;` — that page theme doesn't change to the `light` theme.

If console log the the theme being forced

```js
import { ThemeProvider } from 'next-themes';

function MyApp({ Component, pageProps }) {
	console.log(`Component.theme`, Component.theme);
	return (
		<ThemeProvider attribute="class" defaultTheme="system" forcedTheme={Component.theme || undefined}>
			<Component {...pageProps} />
		</ThemeProvider>
	);
}

export default MyApp;

```

Then it logs `Component.theme light`. This is not working because of the same caching issue?

**Comment by pacocoursey** [comment]
> The main purpose of this library is to be able to adopt to the user preference

That's not what I built, next-themes is simply a way to work with themes in your Next.js app. System happens to be useful because so many sites use a light and dark mode, but it's an abstraction that should also support a Retro 90s theme, a steampunk theme, synthwave theme, etc.

I agree that making `system` the default may be broadly applicable, but I'm still not convinced. By web defaults, websites are light, and themes are a preference.

> My setup did start working I have no idea how. Bunch of cache removals and then setting themese manually etc

Sorry to hear about this, it shouldn't be this rough. Fixing the caching behavior should help a bit here. I also recommend opening a new Incognito/Private window when testing the `defaultTheme`, as your caches will be reset automatically.

> But when I set Post.theme = light; — that page theme doesn't change to the light theme.

I can't reproduce this behavior. When I copy your provided `_app` into the example site, the forced themes work correctly. Is `Post` the name of the exported React component?

**Comment by ahmadawais** [comment]
> I agree that making system the default may be broadly applicable, but I'm still not convinced. By web defaults, websites are light, and themes are a preference.

I see your point of view now. Hence the name. Makes a lot of sense. It just happens to be an excellent way to build dark mode with Next — maybe I could write a wrapper on top of this. 

It falls on us to build software with sane defaults. I'd recommend reading up on that. WordPress also has a similar philosophy — without sane defaults, we end up with a lot of confusion. Just a recommendation. 

I believe if a user goes out of the way to opt-in for dark mode — it doesn't matter if the web default is light — we should prefer a user's preference. The same is the case with reduced motion preference (not a web default but when chosen by a user, our site should have a sane default to accept that preference and reduce the animations).

>I also recommend opening a new Incognito/Private window when testing the defaultTheme, as your caches will be reset automatically.

It didn't help initially since I didn't know that the `light` theme is considered a sane default instead of the system i.e. user-preference. I think after setting that the deafaultTheme to `system` everything worked.


> Is Post the name of the exported React component?

Yes it is. Hence I wonder what's causing it. It's a dynamic route `[slug].js` with `Post` component.

**Comment by trm217** [comment]
I fail to see a usecase where one would want to set a default theme different than system when "enableSystem" is set to true.
Perhaps it would make sense to utilize "light" as a default value if neither defaultTheme nor enableSystem (or enableSystem is equal to false) are set. And when enableSystem is set without defaultTheme being set manually use "system" as the default theme.
What do you think @pacocoursey?

**Comment by pacocoursey** [comment]
I published `0.0.13-beta.1` with the following changes:
- `system` is now the default theme is `enableSystem === true`, otherwise it's still `light`
- The default theme is not immediately saved to `localStorage` on first load, only when you switch theme

These should resolve this issue. Please test, and let me know if you have any feedback.

**Comment by trm217** [comment]
Thanks a lot! Good stuff 💯🔥

**Comment by ahmadawais** [comment]
Excellent, I think this is fantastic

**Comment by trm217** [comment]
@pacocoursey I tested the branch 0.0.13, worked fine for me.
I suppose this issue could be closed now?

**Comment by snigdha920** [comment]
I am still facing this issue, this is what my ThemeProvider looks like:
```
<ThemeProvider
                    attribute="class"
                    storageKey="nightwind-mode"
                    defaultTheme="system"
                    enableSystem={true}
                  >
                    <Component {...pageProps} key={router.route} />
                  </ThemeProvider>
```
And nightwind mode still saves `light` in localstorage on initial reload :
<img width="209" alt="Screenshot 2021-06-21 at 1 45 55 AM" src="https://user-images.githubusercontent.com/62167899/122687145-8e263b00-d232-11eb-8339-1bb660771d3d.png">

**Comment by pacocoursey** [comment]
That's strange @snigdha920, what version are you using? Try upgrading to the latest if you're not already via

```
yarn add next-themes@latest
```

**Comment by snigdha920** [comment]
I upgraded it, it works as expected when I open my website in the 'light' mode, and then toggle the themes - the changes are applied. 

However, when I open my website in dark mode - and I change my theme for the first time, I need to refresh my page for the styling changes to get applied. After the first refresh, it toggles automatically without refresh - as expected.

Maybe something is missing?

**Comment by snigdha920** [comment]
Ah okay, I resolved it. The issue was on my end. 

For future reference - while using next.js if you have Providers wraping your ` <Component {...pageProps} key={router.route} />` in `_app` and these Providers render some components, make sure to wrap such Providers in the ThemeProvider or else the themes won't be applied.

Example: 

if your AuthProvider returns some component the ThemeProvider won't apply the themes on those components when nested as: 
```
<AuthProvider>
<ThemeProvider>
<Component />
</ThemeProvider>
</AuthProvider>
```

To apply the themes for components returned by AuthProvider as well we have to nest it as : 
```
<ThemeProvider>
<AuthProvider>
<Component />
</AuthProvider>
</ThemeProvider>
```
This may seem trivial, but it caused quite some issues so it's good to be aware ;)

**Comment by pacocoursey** [comment]
Ah yep, glad you found the issue!

**Comment by rickyzhangca** [comment]
if still have trouble using

```
<ThemeProvider attribute="class">
   ...
</ThemeProvider>
```

the theme resolving doesn't consider system theme 

![image](https://github.com/pacocoursey/next-themes/assets/16908811/931e1760-6e8d-43fc-ac2b-03c0538e5d29)

**Comment by rickyzhangca** [comment]
> @rickyzhangca if `theme == 'system'` then `resolvedTheme` will resolve to the system-theme. In the case of your screenshot, `theme=light` applies, so the system theme won't apply. Run `setTheme('system')` and it should work fine.

thank you for the hint, I wen to clear localstorage and worked fine, probably got messy when testing things

**Comment by mambucodev** [comment]
@pacocoursey I'm kinda having this issue too... it wasn't completely solved.
I'm using it affiliated with shadcn/ui.
Nothing is stored in the local storage, but if I set defaultTheme as system, I just see it light.

_app.tsx
```tsx
<ThemeProvider
  attribute="class"
  defaultTheme="system"
  enableSystem
  enableColorScheme
>
  {/* Stuff */}
</ThemeProvider>
```
![screenshot](https://github.com/user-attachments/assets/da606401-f835-4ade-9f1e-b75cbfea410b)
